---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/sheen-dhas/Big-Data-devops.git

- name: build-spark
  type: docker-image
  source:
    repository: debrooy/docker-create-concourse-hbase-image

jobs:
- name: run-git
  public: true
  plan:
  - get: build-spark
  - get: resource-tutorial
  - task: run
    file: resource-tutorial/hbase_devops/hbase_pipeline.yml